PREFIX my_ns: <uri:xinting_myunghee:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

SELECT ?name ?se_ds ?title
WHERE {
  ?uri a my_ns:job ;
       my_ns:company <uri:xinting_myunghee:1010data> .
  ?uri my_ns:se_ds ?se_ds ;
       my_ns:job_title ?title.
  
  <uri:xinting_myunghee:1010data> schema:name ?name

}
